### ISSUE TITLE
0.9.20.1.1 - crash

### ISSUE THREAD

**Issue by DrLivesey2** [smellyriver/tankinspector#13]
After patch with Halloween content - Tank Inspector is crash down :(
[sti.log](https://github.com/smellyriver/tankinspector/files/1423711/sti.log)
maybe this is related to multi-towers FCM F1 and Char 2c

**Comment by TwistedAndy** [comment]
I have the same problem with version 0.9.20.1.1 . Seems like it caused by two multi-tower tanks.
