### ISSUE TITLE
Crash Caused by New Update

### ISSUE THREAD

**Issue by LeoPardII** [smellyriver/tankinspector#16]
Update 1.0 has many tank model changes and HD changes, Tank inspector seems to be unable to read the new set up, as it crashes soon after start.

**Comment by adri1wcrow** [comment]
Waiting for the 1.0 update published in China to repair.

**Comment by LeoPardII** [comment]
@adri1wcrow Hopefully it is soon

**Comment by adri1wcrow** [comment]
@LeoPardII It seems that the update won't published at China before May. I will try to fix it this weekend.

**Comment by hillin** [comment]
@adri1wcrow thanks! I've been a bit far away from WOT now...

**Comment by LeoPardII** [comment]
Tell me when it can be used again ^^

**Comment by LeoPardII** [comment]
Sorry, hit wrong button

**Comment by adri1wcrow** [comment]
@LeoPardII It should be fixed already by the newest commit.
You can compile the source code to use it.
The release version may be tomorrow.

**Comment by LeoPardII** [comment]
I will wait for the new version. I am no coder ^^
