### ISSUE TITLE
停止工作

### ISSUE THREAD

**Issue by CIJIANG** [smellyriver/tankinspector#4]
![21hxvrb2u45kfv b_ hi u](https://cloud.githubusercontent.com/assets/28707551/26058930/75b5730a-39b2-11e7-89e4-5572f43792ee.png)

**Comment by hillin** [comment]
你好，
最新的版本已经修正了这个问题。请更新：https://github.com/smellyriver/tankinspector/releases/tag/1.8.1

(Duplicated with #2 )
