### ISSUE TITLE
Can't switch ammo type when checking the effective armor

### ISSUE THREAD

**Issue by Kazfyx** [smellyriver/tankinspector#6]
![image](https://cloud.githubusercontent.com/assets/16810312/26711481/215c0e2e-4793-11e7-8b27-e79f1f3915c2.png)
The ammo type can't be changed, it's always AP.

And there is an old problem: the vehicle camouflage in tankinspector doesn't match the value in the wot client.

**Comment by hillin** [comment]
Fixed https://github.com/smellyriver/tankinspector/commit/f2a93b1f04fbb3d55b9d73207cc39f054220a2e9

Grab a release here: https://github.com/smellyriver/tankinspector/releases/tag/1.9.0
